### ISSUE TITLE
Create central style file for new palette and new gradient files.

### ISSUE THREAD

**Issue by NiallEccles** [NiallEccles/kleur#10]
Currently in the project there are two components - New Palette and New Gradient. They both have separate style files despite both having extremely similar classes and styles. For consistency and ease, it would be beneficial if there was one central file both components used. Both of these components can be found on the `/new` route.

Updates should be made on a new branch called `feature/central-palette-gradient-style`.

**Comment by shinobig** [comment]
Hi, I'm interested in your project, I like it. 
Basically what you need is to refactor those two files, to consume only one 
I took a look at the files and there are a couple other components that might need refactor too, like the paleteIcon and the colourPicker. 
If it's not urgent, I can give you a hand, because it may take me a couple days.

**Comment by NiallEccles** [comment]
@shinobig sure thing!

This is not urgent so take your time!

**Comment by shinobig** [comment]
Hello, I just finished the refactoring, would you please assign me the task so I can push the branch?

**Comment by NiallEccles** [comment]
@shinobig you are assigned! Let me know if you have any issues!

**Comment by shinobig** [comment]
Ready to merge! if you have any questions please let me know!
https://github.com/NiallEccles/kleur/pull/13

**Comment by NiallEccles** [comment]
#13  That has been merged! Excellent work!
